import type { Metadata } from "next";

export const homepageMetadata: Metadata = {
  title: "STGO Fine Art | Impresión y Enmarcado Profesional de Arte",
  description: "Fotografía de arte fino de alta resolución, impresión profesional, enmarcado y servicios de instalación. Imprenta especializada en arte, impresión fine art, enramado y marcos personalizados. Servicios de impresión, enmarcado y arte decorativo.",
  keywords: [
    "fine art",
    "arte",
    "arts",
    "imprenta",
    "imprenta chile",
    "imprenta santiago",
    "imprenta profesional chile",
    "imprenta arte chile",
    "impresión",
    "impresión chile",
    "impresión santiago",
    "impresión profesional chile",
    "impresión fine art chile",
    "impresion",
    "enramado",
    "enramado chile",
    "enramado santiago",
    "enmarcado",
    "enmarcado chile",
    "enmarcado santiago",
    "enmarcado profesional chile",
    "marcos",
    "marcos chile",
    "marcos personalizados chile",
    "fotografía artística",
    "fotografía artística chile",
    "arte fino",
    "impresión profesional",
    "enmarcado profesional",
    "impresión fine art",
    "arte decorativo",
    "arte decorativo chile",
    "fotografía de alta resolución",
    "impresión en canvas",
    "impresión canvas chile",
    "marcos personalizados",
    "arte para decoración",
    "impresión museo",
    "impresión museo chile",
    "imprenta fine art",
    "imprenta fine art chile",
    "servicios imprenta chile",
    "impresión profesional santiago",
  ],
};

